/**
 * Mazzo viaggio — Italiano / Cinese / Pinyin
 * Categorie allineate al piano 12 settimane (gruppo, free).
 */
window.TRAVEL_CARDS = [
  // —— Sopravvivenza ——
  { id: "s01", cat: "sopravvivenza", it: "Ciao / Salve", zh: "你好", py: "nǐ hǎo" },
  { id: "s02", cat: "sopravvivenza", it: "Buongiorno (formale)", zh: "您好", py: "nín hǎo" },
  { id: "s03", cat: "sopravvivenza", it: "Grazie", zh: "谢谢", py: "xièxie" },
  { id: "s04", cat: "sopravvivenza", it: "Prego / Di niente", zh: "不客气", py: "bú kèqi" },
  { id: "s05", cat: "sopravvivenza", it: "Scusa / Scusi", zh: "不好意思", py: "bù hǎoyìsi" },
  { id: "s06", cat: "sopravvivenza", it: "Mi dispiace", zh: "对不起", py: "duìbuqǐ" },
  { id: "s07", cat: "sopravvivenza", it: "Per favore", zh: "请", py: "qǐng" },
  { id: "s08", cat: "sopravvivenza", it: "Va bene? / Posso?", zh: "可以吗？", py: "kěyǐ ma?" },
  { id: "s09", cat: "sopravvivenza", it: "Sì", zh: "是", py: "shì" },
  { id: "s10", cat: "sopravvivenza", it: "No / Non è così", zh: "不是", py: "bú shì" },
  { id: "s11", cat: "sopravvivenza", it: "Ok / Va bene", zh: "好的", py: "hǎo de" },
  { id: "s12", cat: "sopravvivenza", it: "Non capisco", zh: "我听不懂", py: "wǒ tīng bù dǒng" },
  { id: "s13", cat: "sopravvivenza", it: "Parli più lentamente, per favore", zh: "请说慢一点", py: "qǐng shuō màn yìdiǎn" },
  { id: "s14", cat: "sopravvivenza", it: "Parli inglese?", zh: "你会说英语吗？", py: "nǐ huì shuō Yīngyǔ ma?" },
  { id: "s15", cat: "sopravvivenza", it: "Non lo so", zh: "我不知道", py: "wǒ bù zhīdào" },
  { id: "s16", cat: "sopravvivenza", it: "Aiuto!", zh: "帮忙！", py: "bāngmáng!" },
  { id: "s17", cat: "sopravvivenza", it: "Può aiutarmi?", zh: "可以帮忙吗？", py: "kěyǐ bāngmáng ma?" },
  { id: "s18", cat: "sopravvivenza", it: "Dov'è il bagno?", zh: "洗手间在哪里？", py: "xǐshǒujiān zài nǎlǐ?" },
  { id: "s19", cat: "sopravvivenza", it: "Mi sono perso/a", zh: "我迷路了", py: "wǒ mílù le" },
  { id: "s20", cat: "sopravvivenza", it: "Nessun problema", zh: "没关系", py: "méi guānxi" },

  // —— Numeri e soldi ——
  { id: "n01", cat: "numeri", it: "Zero", zh: "零", py: "líng" },
  { id: "n02", cat: "numeri", it: "Uno", zh: "一", py: "yī" },
  { id: "n03", cat: "numeri", it: "Due", zh: "二", py: "èr" },
  { id: "n04", cat: "numeri", it: "Tre", zh: "三", py: "sān" },
  { id: "n05", cat: "numeri", it: "Quattro", zh: "四", py: "sì" },
  { id: "n06", cat: "numeri", it: "Cinque", zh: "五", py: "wǔ" },
  { id: "n07", cat: "numeri", it: "Sei", zh: "六", py: "liù" },
  { id: "n08", cat: "numeri", it: "Sette", zh: "七", py: "qī" },
  { id: "n09", cat: "numeri", it: "Otto", zh: "八", py: "bā" },
  { id: "n10", cat: "numeri", it: "Nove", zh: "九", py: "jiǔ" },
  { id: "n11", cat: "numeri", it: "Dieci", zh: "十", py: "shí" },
  { id: "n12", cat: "numeri", it: "Venti", zh: "二十", py: "èrshí" },
  { id: "n13", cat: "numeri", it: "Cento", zh: "一百", py: "yìbǎi" },
  { id: "n14", cat: "numeri", it: "Quanto costa?", zh: "多少钱？", py: "duōshao qián?" },
  { id: "n15", cat: "numeri", it: "Quanto costa questo?", zh: "这个多少钱？", py: "zhège duōshao qián?" },
  { id: "n16", cat: "numeri", it: "Troppo caro", zh: "太贵了", py: "tài guì le" },
  { id: "n17", cat: "numeri", it: "Un po' meno, si può?", zh: "便宜一点可以吗？", py: "piányi yìdiǎn kěyǐ ma?" },
  { id: "n18", cat: "numeri", it: "Posso pagare con la carta?", zh: "可以刷卡吗？", py: "kěyǐ shuākǎ ma?" },
  { id: "n19", cat: "numeri", it: "Contanti", zh: "现金", py: "xiànjīn" },
  { id: "n20", cat: "numeri", it: "Scontrino / ricevuta", zh: "收据", py: "shōujù" },

  // —— Cibo ——
  { id: "f01", cat: "cibo", it: "Siamo in X persone", zh: "我们有几个人", py: "wǒmen yǒu jǐ ge rén" },
  { id: "f02", cat: "cibo", it: "Il menu, per favore", zh: "菜单", py: "càidān" },
  { id: "f03", cat: "cibo", it: "Vorrei ordinare", zh: "点菜", py: "diǎn cài" },
  { id: "f04", cat: "cibo", it: "Prendo questo", zh: "我要这个", py: "wǒ yào zhège" },
  { id: "f05", cat: "cibo", it: "Non piccante", zh: "不要辣", py: "bú yào là" },
  { id: "f06", cat: "cibo", it: "Poco piccante", zh: "微辣", py: "wēi là" },
  { id: "f07", cat: "cibo", it: "Senza carne", zh: "不要肉", py: "bú yào ròu" },
  { id: "f08", cat: "cibo", it: "Sono vegetariano/a", zh: "我吃素", py: "wǒ chī sù" },
  { id: "f09", cat: "cibo", it: "Riso", zh: "米饭", py: "mǐfàn" },
  { id: "f10", cat: "cibo", it: "Acqua", zh: "水", py: "shuǐ" },
  { id: "f11", cat: "cibo", it: "Birra", zh: "啤酒", py: "píjiǔ" },
  { id: "f12", cat: "cibo", it: "Tè", zh: "茶", py: "chá" },
  { id: "f13", cat: "cibo", it: "Il conto, per favore", zh: "买单", py: "mǎidān" },
  { id: "f14", cat: "cibo", it: "Paghiamo insieme", zh: "一起付", py: "yìqǐ fù" },
  { id: "f15", cat: "cibo", it: "Delizioso!", zh: "很好吃！", py: "hěn hǎochī!" },
  { id: "f16", cat: "cibo", it: "Non è piccante?", zh: "辣不辣？", py: "là bu là?" },
  { id: "f17", cat: "cibo", it: "Un altro, per favore", zh: "再来一个", py: "zài lái yí ge" },
  { id: "f18", cat: "cibo", it: "Basta così", zh: "够了", py: "gòu le" },
  { id: "f19", cat: "cibo", it: "Posso avere i bastoncini?", zh: "筷子", py: "kuàizi" },
  { id: "f20", cat: "cibo", it: "Acqua calda", zh: "热水", py: "rè shuǐ" },

  // —— Trasporti ——
  { id: "t01", cat: "trasporti", it: "Vogliamo andare a…", zh: "我们要去……", py: "wǒmen yào qù…" },
  { id: "t02", cat: "trasporti", it: "Aeroporto", zh: "机场", py: "jīchǎng" },
  { id: "t03", cat: "trasporti", it: "Stazione ferroviaria", zh: "火车站", py: "huǒchēzhàn" },
  { id: "t04", cat: "trasporti", it: "Hotel", zh: "酒店", py: "jiǔdiàn" },
  { id: "t05", cat: "trasporti", it: "Metropolitana / fermata metro", zh: "地铁站", py: "dìtiězhàn" },
  { id: "t06", cat: "trasporti", it: "Per favore vada qui", zh: "请到这里", py: "qǐng dào zhèlǐ" },
  { id: "t07", cat: "trasporti", it: "Quanto costa arrivare a…?", zh: "多少钱到……？", py: "duōshao qián dào…?" },
  { id: "t08", cat: "trasporti", it: "Gira a sinistra", zh: "左转", py: "zuǒ zhuǎn" },
  { id: "t09", cat: "trasporti", it: "Gira a destra", zh: "右转", py: "yòu zhuǎn" },
  { id: "t10", cat: "trasporti", it: "Vai dritto", zh: "直走", py: "zhí zǒu" },
  { id: "t11", cat: "trasporti", it: "Questa fermata", zh: "这站", py: "zhè zhàn" },
  { id: "t12", cat: "trasporti", it: "Prossima fermata", zh: "下一站", py: "xià yī zhàn" },
  { id: "t13", cat: "trasporti", it: "Dov'è…?", zh: "在哪里？", py: "zài nǎlǐ?" },
  { id: "t14", cat: "trasporti", it: "Taxi", zh: "出租车", py: "chūzūchē" },
  { id: "t15", cat: "trasporti", it: "Biglietto", zh: "票", py: "piào" },
  { id: "t16", cat: "trasporti", it: "Entrata", zh: "入口", py: "rùkǒu" },
  { id: "t17", cat: "trasporti", it: "Uscita", zh: "出口", py: "chūkǒu" },
  { id: "t18", cat: "trasporti", it: "Aspetta un attimo", zh: "等一下", py: "děng yíxià" },
  { id: "t19", cat: "trasporti", it: "Più veloce / in fretta", zh: "快点", py: "kuài diǎn" },
  { id: "t20", cat: "trasporti", it: "Qui / là", zh: "这里 / 那里", py: "zhèlǐ / nàlǐ" },

  // —— Hotel e shopping ——
  { id: "h01", cat: "hotel", it: "Abbiamo una prenotazione", zh: "我们有预订", py: "wǒmen yǒu yùdìng" },
  { id: "h02", cat: "hotel", it: "Camera", zh: "房间", py: "fángjiān" },
  { id: "h03", cat: "hotel", it: "Password del Wi‑Fi", zh: "Wi‑Fi 密码", py: "Wi‑Fi mìmǎ" },
  { id: "h04", cat: "hotel", it: "Posso dare un'occhiata?", zh: "可以看看吗？", py: "kěyǐ kànkan ma?" },
  { id: "h05", cat: "hotel", it: "Un po' più grande", zh: "大一点", py: "dà yìdiǎn" },
  { id: "h06", cat: "hotel", it: "Un po' più piccolo", zh: "小一点", py: "xiǎo yìdiǎn" },
  { id: "h07", cat: "hotel", it: "Sto solo guardando", zh: "我只是看看", py: "wǒ zhǐshì kànkan" },
  { id: "h08", cat: "hotel", it: "Fattura", zh: "发票", py: "fāpiào" },
  { id: "h09", cat: "hotel", it: "Check-in", zh: "入住", py: "rùzhù" },
  { id: "h10", cat: "hotel", it: "Check-out", zh: "退房", py: "tuìfáng" },
  { id: "h11", cat: "hotel", it: "Ascensore", zh: "电梯", py: "diàntī" },
  { id: "h12", cat: "hotel", it: "Chiave della camera", zh: "房卡", py: "fángkǎ" },

  // —— Social / gruppo ——
  { id: "g01", cat: "social", it: "Possiamo fare una foto?", zh: "可以拍照吗？", py: "kěyǐ pāizhào ma?" },
  { id: "g02", cat: "social", it: "Bellissimo!", zh: "很漂亮！", py: "hěn piàoliang!" },
  { id: "g03", cat: "social", it: "Siamo turisti", zh: "我们是游客", py: "wǒmen shì yóukè" },
  { id: "g04", cat: "social", it: "Veniamo dall'Italia", zh: "我们从意大利来", py: "wǒmen cóng Yìdàlì lái" },
  { id: "g05", cat: "social", it: "Molto bene", zh: "很好", py: "hěn hǎo" },
  { id: "g06", cat: "social", it: "Non male", zh: "不错", py: "búcuò" },
  { id: "g07", cat: "social", it: "La connessione è scarsa", zh: "网络不好", py: "wǎngluò bù hǎo" },
  { id: "g08", cat: "social", it: "Il telefono è scarico", zh: "手机没电了", py: "shǒujī méi diàn le" },
  { id: "g09", cat: "social", it: "Come ti chiami?", zh: "你叫什么名字？", py: "nǐ jiào shénme míngzi?" },
  { id: "g10", cat: "social", it: "Piacere di conoscerti", zh: "很高兴认识你", py: "hěn gāoxìng rènshi nǐ" },
  { id: "g11", cat: "social", it: "A dopo / Ciao (andando via)", zh: "再见", py: "zàijiàn" },
  { id: "g12", cat: "social", it: "Siamo un gruppo", zh: "我们是一个团队", py: "wǒmen shì yí ge tuánduì" },
];

window.CAT_LABELS = {
  all: "Tutte",
  sopravvivenza: "Sopravvivenza",
  numeri: "Numeri e soldi",
  cibo: "Cibo",
  trasporti: "Trasporti",
  hotel: "Hotel e shopping",
  social: "Social / gruppo",
};
