/**
 * Mazzo viaggio — Italiano / Cinese / Pinyin + gloss per parola
 * Categorie allineate al piano 12 settimane (gruppo, free).
 *
 * words[]: tocchi una parola sulla carta per vedere pinyin + italiano.
 * I segni di punteggiatura hanno py/it vuoti e non sono cliccabili.
 */
const w = (zh, py, it) => ({ zh, py, it });
const p = (zh) => ({ zh, py: "", it: "" });

window.TRAVEL_CARDS = [
  // —— Sopravvivenza ——
  { id: "s01", cat: "sopravvivenza", it: "Ciao / Salve", zh: "你好", py: "nǐ hǎo",
    words: [w("你", "nǐ", "tu"), w("好", "hǎo", "bene")] },
  { id: "s02", cat: "sopravvivenza", it: "Buongiorno (formale)", zh: "您好", py: "nín hǎo",
    words: [w("您", "nín", "Lei (formale)"), w("好", "hǎo", "bene")] },
  { id: "s03", cat: "sopravvivenza", it: "Grazie", zh: "谢谢", py: "xièxie",
    words: [w("谢谢", "xièxie", "grazie")] },
  { id: "s04", cat: "sopravvivenza", it: "Prego / Di niente", zh: "不客气", py: "bú kèqi",
    words: [w("不", "bú", "non"), w("客气", "kèqi", "formale / cerimonioso")] },
  { id: "s05", cat: "sopravvivenza", it: "Scusa / Scusi", zh: "不好意思", py: "bù hǎoyìsi",
    words: [w("不好意思", "bù hǎoyìsi", "scusa / che imbarazzo")] },
  { id: "s06", cat: "sopravvivenza", it: "Mi dispiace", zh: "对不起", py: "duìbuqǐ",
    words: [w("对不起", "duìbuqǐ", "mi dispiace")] },
  { id: "s07", cat: "sopravvivenza", it: "Per favore", zh: "请", py: "qǐng",
    words: [w("请", "qǐng", "per favore / prego")] },
  { id: "s08", cat: "sopravvivenza", it: "Va bene? / Posso?", zh: "可以吗？", py: "kěyǐ ma?",
    words: [w("可以", "kěyǐ", "si può / potere"), w("吗", "ma", "particella di domanda"), p("？")] },
  { id: "s09", cat: "sopravvivenza", it: "Sì", zh: "是", py: "shì",
    words: [w("是", "shì", "essere / sì")] },
  { id: "s10", cat: "sopravvivenza", it: "No / Non è così", zh: "不是", py: "bú shì",
    words: [w("不", "bú", "non"), w("是", "shì", "essere")] },
  { id: "s11", cat: "sopravvivenza", it: "Ok / Va bene", zh: "好的", py: "hǎo de",
    words: [w("好", "hǎo", "bene"), w("的", "de", "particella")] },
  { id: "s12", cat: "sopravvivenza", it: "Non capisco", zh: "我听不懂", py: "wǒ tīng bù dǒng",
    words: [w("我", "wǒ", "io"), w("听", "tīng", "ascoltare"), w("不", "bù", "non"), w("懂", "dǒng", "capire")] },
  { id: "s13", cat: "sopravvivenza", it: "Parli più lentamente, per favore", zh: "请说慢一点", py: "qǐng shuō màn yìdiǎn",
    words: [w("请", "qǐng", "per favore"), w("说", "shuō", "parlare / dire"), w("慢", "màn", "lento"), w("一点", "yìdiǎn", "un po'")] },
  { id: "s14", cat: "sopravvivenza", it: "Parli inglese?", zh: "你会说英语吗？", py: "nǐ huì shuō Yīngyǔ ma?",
    words: [w("你", "nǐ", "tu"), w("会", "huì", "sapere fare"), w("说", "shuō", "parlare"), w("英语", "Yīngyǔ", "inglese"), w("吗", "ma", "particella di domanda"), p("？")] },
  { id: "s15", cat: "sopravvivenza", it: "Non lo so", zh: "我不知道", py: "wǒ bù zhīdào",
    words: [w("我", "wǒ", "io"), w("不", "bù", "non"), w("知道", "zhīdào", "sapere")] },
  { id: "s16", cat: "sopravvivenza", it: "Aiuto!", zh: "帮忙！", py: "bāngmáng!",
    words: [w("帮忙", "bāngmáng", "aiutare / dare una mano"), p("！")] },
  { id: "s17", cat: "sopravvivenza", it: "Può aiutarmi?", zh: "可以帮忙吗？", py: "kěyǐ bāngmáng ma?",
    words: [w("可以", "kěyǐ", "si può"), w("帮忙", "bāngmáng", "aiutare"), w("吗", "ma", "particella di domanda"), p("？")] },
  { id: "s18", cat: "sopravvivenza", it: "Dov'è il bagno?", zh: "洗手间在哪里？", py: "xǐshǒujiān zài nǎlǐ?",
    words: [w("洗手间", "xǐshǒujiān", "bagno / toilette"), w("在", "zài", "trovarsi / essere a"), w("哪里", "nǎlǐ", "dove"), p("？")] },
  { id: "s19", cat: "sopravvivenza", it: "Mi sono perso/a", zh: "我迷路了", py: "wǒ mílù le",
    words: [w("我", "wǒ", "io"), w("迷路", "mílù", "perdersi"), w("了", "le", "particella (già successo)")] },
  { id: "s20", cat: "sopravvivenza", it: "Nessun problema", zh: "没关系", py: "méi guānxi",
    words: [w("没关系", "méi guānxi", "non fa niente / nessun problema")] },
  { id: "s21", cat: "sopravvivenza", it: "Non parlo cinese", zh: "我不会说中文", py: "wǒ bú huì shuō Zhōngwén",
    words: [w("我", "wǒ", "io"), w("不", "bú", "non"), w("会", "huì", "sapere / essere in grado"), w("说", "shuō", "parlare"), w("中文", "Zhōngwén", "cinese")] },
  { id: "s22", cat: "sopravvivenza", it: "Mi fa male qui", zh: "我这里疼", py: "wǒ zhèlǐ téng",
    words: [w("我", "wǒ", "io"), w("这里", "zhèlǐ", "qui"), w("疼", "téng", "fare male")] },
  { id: "s23", cat: "sopravvivenza", it: "Dov'è una farmacia?", zh: "药店在哪里？", py: "yàodiàn zài nǎlǐ?",
    words: [w("药店", "yàodiàn", "farmacia"), w("在", "zài", "trovarsi / essere a"), w("哪里", "nǎlǐ", "dove"), p("？")] },

  // —— Numeri e soldi ——
  { id: "n01", cat: "numeri", it: "Zero", zh: "零", py: "líng", words: [w("零", "líng", "zero")] },
  { id: "n02", cat: "numeri", it: "Uno", zh: "一", py: "yī", words: [w("一", "yī", "uno")] },
  { id: "n03", cat: "numeri", it: "Due", zh: "二", py: "èr", words: [w("二", "èr", "due")] },
  { id: "n04", cat: "numeri", it: "Tre", zh: "三", py: "sān", words: [w("三", "sān", "tre")] },
  { id: "n05", cat: "numeri", it: "Quattro", zh: "四", py: "sì", words: [w("四", "sì", "quattro")] },
  { id: "n06", cat: "numeri", it: "Cinque", zh: "五", py: "wǔ", words: [w("五", "wǔ", "cinque")] },
  { id: "n07", cat: "numeri", it: "Sei", zh: "六", py: "liù", words: [w("六", "liù", "sei")] },
  { id: "n08", cat: "numeri", it: "Sette", zh: "七", py: "qī", words: [w("七", "qī", "sette")] },
  { id: "n09", cat: "numeri", it: "Otto", zh: "八", py: "bā", words: [w("八", "bā", "otto")] },
  { id: "n10", cat: "numeri", it: "Nove", zh: "九", py: "jiǔ", words: [w("九", "jiǔ", "nove")] },
  { id: "n11", cat: "numeri", it: "Dieci", zh: "十", py: "shí", words: [w("十", "shí", "dieci")] },
  { id: "n12", cat: "numeri", it: "Venti", zh: "二十", py: "èrshí",
    words: [w("二", "èr", "due"), w("十", "shí", "dieci")] },
  { id: "n13", cat: "numeri", it: "Cento", zh: "一百", py: "yìbǎi",
    words: [w("一", "yì", "uno"), w("百", "bǎi", "cento")] },
  { id: "n14", cat: "numeri", it: "Quanto costa?", zh: "多少钱？", py: "duōshao qián?",
    words: [w("多少", "duōshao", "quanto"), w("钱", "qián", "soldi"), p("？")] },
  { id: "n15", cat: "numeri", it: "Quanto costa questo?", zh: "这个多少钱？", py: "zhège duōshao qián?",
    words: [w("这个", "zhège", "questo"), w("多少", "duōshao", "quanto"), w("钱", "qián", "soldi"), p("？")] },
  { id: "n16", cat: "numeri", it: "Troppo caro", zh: "太贵了", py: "tài guì le",
    words: [w("太", "tài", "troppo"), w("贵", "guì", "caro"), w("了", "le", "particella (enfasi)")] },
  { id: "n17", cat: "numeri", it: "Un po' meno, si può?", zh: "便宜一点可以吗？", py: "piányi yìdiǎn kěyǐ ma?",
    words: [w("便宜", "piányi", "economico"), w("一点", "yìdiǎn", "un po'"), w("可以", "kěyǐ", "si può"), w("吗", "ma", "particella di domanda"), p("？")] },
  { id: "n18", cat: "numeri", it: "Posso pagare con la carta?", zh: "可以刷卡吗？", py: "kěyǐ shuākǎ ma?",
    words: [w("可以", "kěyǐ", "si può"), w("刷卡", "shuākǎ", "pagare con la carta"), w("吗", "ma", "particella di domanda"), p("？")] },
  { id: "n19", cat: "numeri", it: "Contanti", zh: "现金", py: "xiànjīn",
    words: [w("现金", "xiànjīn", "contanti")] },
  { id: "n20", cat: "numeri", it: "Scontrino / ricevuta", zh: "收据", py: "shōujù",
    words: [w("收据", "shōujù", "scontrino / ricevuta")] },
  { id: "n21", cat: "numeri", it: "Posso pagare con Alipay / WeChat?", zh: "可以用支付宝或微信吗？", py: "kěyǐ yòng Zhīfùbǎo huò Wēixìn ma?",
    words: [w("可以", "kěyǐ", "si può"), w("用", "yòng", "usare"), w("支付宝", "Zhīfùbǎo", "Alipay"), w("或", "huò", "oppure"), w("微信", "Wēixìn", "WeChat"), w("吗", "ma", "particella di domanda"), p("？")] },

  // —— Cibo ——
  { id: "f01", cat: "cibo", it: "Siamo in X persone", zh: "我们有几个人", py: "wǒmen yǒu jǐ ge rén",
    words: [w("我们", "wǒmen", "noi"), w("有", "yǒu", "avere"), w("几", "jǐ", "quanti / alcuni"), w("个", "ge", "classificatore"), w("人", "rén", "persona / persone")] },
  { id: "f02", cat: "cibo", it: "Il menu, per favore", zh: "菜单", py: "càidān",
    words: [w("菜单", "càidān", "menu")] },
  { id: "f03", cat: "cibo", it: "Vorrei ordinare", zh: "点菜", py: "diǎn cài",
    words: [w("点", "diǎn", "ordinare"), w("菜", "cài", "piatti / cibo")] },
  { id: "f04", cat: "cibo", it: "Prendo questo", zh: "我要这个", py: "wǒ yào zhège",
    words: [w("我", "wǒ", "io"), w("要", "yào", "volere"), w("这个", "zhège", "questo")] },
  { id: "f05", cat: "cibo", it: "Non piccante", zh: "不要辣", py: "bú yào là",
    words: [w("不", "bú", "non"), w("要", "yào", "volere"), w("辣", "là", "piccante")] },
  { id: "f06", cat: "cibo", it: "Poco piccante", zh: "微辣", py: "wēi là",
    words: [w("微", "wēi", "poco / lieve"), w("辣", "là", "piccante")] },
  { id: "f07", cat: "cibo", it: "Senza carne", zh: "不要肉", py: "bú yào ròu",
    words: [w("不", "bú", "non"), w("要", "yào", "volere"), w("肉", "ròu", "carne")] },
  { id: "f08", cat: "cibo", it: "Sono vegetariano/a", zh: "我吃素", py: "wǒ chī sù",
    words: [w("我", "wǒ", "io"), w("吃", "chī", "mangiare"), w("素", "sù", "vegetariano")] },
  { id: "f09", cat: "cibo", it: "Riso", zh: "米饭", py: "mǐfàn",
    words: [w("米饭", "mǐfàn", "riso cotto")] },
  { id: "f10", cat: "cibo", it: "Acqua", zh: "水", py: "shuǐ",
    words: [w("水", "shuǐ", "acqua")] },
  { id: "f11", cat: "cibo", it: "Birra", zh: "啤酒", py: "píjiǔ",
    words: [w("啤酒", "píjiǔ", "birra")] },
  { id: "f12", cat: "cibo", it: "Tè", zh: "茶", py: "chá",
    words: [w("茶", "chá", "tè")] },
  { id: "f13", cat: "cibo", it: "Il conto, per favore", zh: "买单", py: "mǎidān",
    words: [w("买单", "mǎidān", "il conto / pagare")] },
  { id: "f14", cat: "cibo", it: "Paghiamo insieme", zh: "一起付", py: "yìqǐ fù",
    words: [w("一起", "yìqǐ", "insieme"), w("付", "fù", "pagare")] },
  { id: "f15", cat: "cibo", it: "Delizioso!", zh: "很好吃！", py: "hěn hǎochī!",
    words: [w("很", "hěn", "molto"), w("好吃", "hǎochī", "buono (da mangiare)"), p("！")] },
  { id: "f16", cat: "cibo", it: "Non è piccante?", zh: "辣不辣？", py: "là bu là?",
    words: [w("辣", "là", "piccante"), w("不", "bu", "non (domanda A-non-A)"), w("辣", "là", "piccante"), p("？")] },
  { id: "f17", cat: "cibo", it: "Un altro, per favore", zh: "再来一个", py: "zài lái yí ge",
    words: [w("再", "zài", "di nuovo"), w("来", "lái", "portare / venire"), w("一", "yí", "uno"), w("个", "ge", "classificatore")] },
  { id: "f18", cat: "cibo", it: "Basta così", zh: "够了", py: "gòu le",
    words: [w("够", "gòu", "basta / sufficiente"), w("了", "le", "particella (completato)")] },
  { id: "f19", cat: "cibo", it: "Posso avere i bastoncini?", zh: "筷子", py: "kuàizi",
    words: [w("筷子", "kuàizi", "bacchette")] },
  { id: "f20", cat: "cibo", it: "Acqua calda", zh: "热水", py: "rè shuǐ",
    words: [w("热", "rè", "caldo"), w("水", "shuǐ", "acqua")] },

  // —— Trasporti ——
  { id: "t01", cat: "trasporti", it: "Vogliamo andare a…", zh: "我们要去……", py: "wǒmen yào qù…",
    words: [w("我们", "wǒmen", "noi"), w("要", "yào", "volere"), w("去", "qù", "andare"), p("……")] },
  { id: "t02", cat: "trasporti", it: "Aeroporto", zh: "机场", py: "jīchǎng",
    words: [w("机场", "jīchǎng", "aeroporto")] },
  { id: "t03", cat: "trasporti", it: "Stazione ferroviaria", zh: "火车站", py: "huǒchēzhàn",
    words: [w("火车", "huǒchē", "treno"), w("站", "zhàn", "stazione / fermata")] },
  { id: "t04", cat: "trasporti", it: "Hotel", zh: "酒店", py: "jiǔdiàn",
    words: [w("酒店", "jiǔdiàn", "hotel")] },
  { id: "t05", cat: "trasporti", it: "Metropolitana / fermata metro", zh: "地铁站", py: "dìtiězhàn",
    words: [w("地铁", "dìtiě", "metropolitana"), w("站", "zhàn", "stazione / fermata")] },
  { id: "t06", cat: "trasporti", it: "Per favore vada qui", zh: "请到这里", py: "qǐng dào zhèlǐ",
    words: [w("请", "qǐng", "per favore"), w("到", "dào", "arrivare a / fino a"), w("这里", "zhèlǐ", "qui")] },
  { id: "t07", cat: "trasporti", it: "Quanto costa arrivare a…?", zh: "多少钱到……？", py: "duōshao qián dào…?",
    words: [w("多少", "duōshao", "quanto"), w("钱", "qián", "soldi"), w("到", "dào", "fino a"), p("……"), p("？")] },
  { id: "t08", cat: "trasporti", it: "Gira a sinistra", zh: "左转", py: "zuǒ zhuǎn",
    words: [w("左", "zuǒ", "sinistra"), w("转", "zhuǎn", "girare")] },
  { id: "t09", cat: "trasporti", it: "Gira a destra", zh: "右转", py: "yòu zhuǎn",
    words: [w("右", "yòu", "destra"), w("转", "zhuǎn", "girare")] },
  { id: "t10", cat: "trasporti", it: "Vai dritto", zh: "直走", py: "zhí zǒu",
    words: [w("直", "zhí", "dritto"), w("走", "zǒu", "camminare / andare")] },
  { id: "t11", cat: "trasporti", it: "Questa fermata", zh: "这站", py: "zhè zhàn",
    words: [w("这", "zhè", "questa"), w("站", "zhàn", "fermata")] },
  { id: "t12", cat: "trasporti", it: "Prossima fermata", zh: "下一站", py: "xià yī zhàn",
    words: [w("下", "xià", "prossima / sotto"), w("一", "yī", "una"), w("站", "zhàn", "fermata")] },
  { id: "t13", cat: "trasporti", it: "Dov'è…?", zh: "在哪里？", py: "zài nǎlǐ?",
    words: [w("在", "zài", "trovarsi / essere a"), w("哪里", "nǎlǐ", "dove"), p("？")] },
  { id: "t14", cat: "trasporti", it: "Taxi", zh: "出租车", py: "chūzūchē",
    words: [w("出租车", "chūzūchē", "taxi")] },
  { id: "t15", cat: "trasporti", it: "Biglietto", zh: "票", py: "piào",
    words: [w("票", "piào", "biglietto")] },
  { id: "t16", cat: "trasporti", it: "Entrata", zh: "入口", py: "rùkǒu",
    words: [w("入口", "rùkǒu", "entrata")] },
  { id: "t17", cat: "trasporti", it: "Uscita", zh: "出口", py: "chūkǒu",
    words: [w("出口", "chūkǒu", "uscita")] },
  { id: "t18", cat: "trasporti", it: "Aspetta un attimo", zh: "等一下", py: "děng yíxià",
    words: [w("等", "děng", "aspettare"), w("一下", "yíxià", "un attimo")] },
  { id: "t19", cat: "trasporti", it: "Più veloce / in fretta", zh: "快点", py: "kuài diǎn",
    words: [w("快", "kuài", "veloce"), w("点", "diǎn", "un po'")] },
  { id: "t20", cat: "trasporti", it: "Qui / là", zh: "这里 / 那里", py: "zhèlǐ / nàlǐ",
    words: [w("这里", "zhèlǐ", "qui"), p(" / "), w("那里", "nàlǐ", "là")] },

  // —— Hotel e shopping ——
  { id: "h01", cat: "hotel", it: "Abbiamo una prenotazione", zh: "我们有预订", py: "wǒmen yǒu yùdìng",
    words: [w("我们", "wǒmen", "noi"), w("有", "yǒu", "avere"), w("预订", "yùdìng", "prenotazione")] },
  { id: "h02", cat: "hotel", it: "Camera", zh: "房间", py: "fángjiān",
    words: [w("房间", "fángjiān", "camera / stanza")] },
  { id: "h03", cat: "hotel", it: "Password del Wi‑Fi", zh: "Wi‑Fi 密码", py: "Wi‑Fi mìmǎ",
    words: [w("Wi‑Fi", "Wi‑Fi", "Wi‑Fi"), p(" "), w("密码", "mìmǎ", "password")] },
  { id: "h04", cat: "hotel", it: "Posso dare un'occhiata?", zh: "可以看看吗？", py: "kěyǐ kànkan ma?",
    words: [w("可以", "kěyǐ", "si può"), w("看看", "kànkan", "dare un'occhiata"), w("吗", "ma", "particella di domanda"), p("？")] },
  { id: "h05", cat: "hotel", it: "Un po' più grande", zh: "大一点", py: "dà yìdiǎn",
    words: [w("大", "dà", "grande"), w("一点", "yìdiǎn", "un po'")] },
  { id: "h06", cat: "hotel", it: "Un po' più piccolo", zh: "小一点", py: "xiǎo yìdiǎn",
    words: [w("小", "xiǎo", "piccolo"), w("一点", "yìdiǎn", "un po'")] },
  { id: "h07", cat: "hotel", it: "Sto solo guardando", zh: "我只是看看", py: "wǒ zhǐshì kànkan",
    words: [w("我", "wǒ", "io"), w("只是", "zhǐshì", "solo / soltanto"), w("看看", "kànkan", "guardare")] },
  { id: "h08", cat: "hotel", it: "Fattura", zh: "发票", py: "fāpiào",
    words: [w("发票", "fāpiào", "fattura fiscale")] },
  { id: "h09", cat: "hotel", it: "Check-in", zh: "入住", py: "rùzhù",
    words: [w("入住", "rùzhù", "check-in / entrare in camera")] },
  { id: "h10", cat: "hotel", it: "Check-out", zh: "退房", py: "tuìfáng",
    words: [w("退房", "tuìfáng", "check-out / lasciare la camera")] },
  { id: "h11", cat: "hotel", it: "Ascensore", zh: "电梯", py: "diàntī",
    words: [w("电梯", "diàntī", "ascensore")] },
  { id: "h12", cat: "hotel", it: "Chiave della camera", zh: "房卡", py: "fángkǎ",
    words: [w("房卡", "fángkǎ", "tessera della camera")] },

  // —— Social / gruppo ——
  { id: "g01", cat: "social", it: "Possiamo fare una foto?", zh: "可以拍照吗？", py: "kěyǐ pāizhào ma?",
    words: [w("可以", "kěyǐ", "si può"), w("拍照", "pāizhào", "fare una foto"), w("吗", "ma", "particella di domanda"), p("？")] },
  { id: "g02", cat: "social", it: "Bellissimo!", zh: "很漂亮！", py: "hěn piàoliang!",
    words: [w("很", "hěn", "molto"), w("漂亮", "piàoliang", "bello / bella"), p("！")] },
  { id: "g03", cat: "social", it: "Siamo turisti", zh: "我们是游客", py: "wǒmen shì yóukè",
    words: [w("我们", "wǒmen", "noi"), w("是", "shì", "essere"), w("游客", "yóukè", "turisti")] },
  { id: "g04", cat: "social", it: "Veniamo dall'Italia", zh: "我们从意大利来", py: "wǒmen cóng Yìdàlì lái",
    words: [w("我们", "wǒmen", "noi"), w("从", "cóng", "da"), w("意大利", "Yìdàlì", "Italia"), w("来", "lái", "venire")] },
  { id: "g05", cat: "social", it: "Molto bene", zh: "很好", py: "hěn hǎo",
    words: [w("很", "hěn", "molto"), w("好", "hǎo", "bene")] },
  { id: "g06", cat: "social", it: "Non male", zh: "不错", py: "búcuò",
    words: [w("不错", "búcuò", "non male / piuttosto bene")] },
  { id: "g07", cat: "social", it: "La connessione è scarsa", zh: "网络不好", py: "wǎngluò bù hǎo",
    words: [w("网络", "wǎngluò", "rete / internet"), w("不", "bù", "non"), w("好", "hǎo", "buono")] },
  { id: "g08", cat: "social", it: "Il telefono è scarico", zh: "手机没电了", py: "shǒujī méi diàn le",
    words: [w("手机", "shǒujī", "telefono"), w("没", "méi", "non avere"), w("电", "diàn", "elettricità / batteria"), w("了", "le", "particella (completato)")] },
  { id: "g09", cat: "social", it: "Come ti chiami?", zh: "你叫什么名字？", py: "nǐ jiào shénme míngzi?",
    words: [w("你", "nǐ", "tu"), w("叫", "jiào", "chiamarsi"), w("什么", "shénme", "che / quale"), w("名字", "míngzi", "nome"), p("？")] },
  { id: "g10", cat: "social", it: "Piacere di conoscerti", zh: "很高兴认识你", py: "hěn gāoxìng rènshi nǐ",
    words: [w("很", "hěn", "molto"), w("高兴", "gāoxìng", "felice"), w("认识", "rènshi", "conoscere"), w("你", "nǐ", "te")] },
  { id: "g11", cat: "social", it: "A dopo / Ciao (andando via)", zh: "再见", py: "zàijiàn",
    words: [w("再", "zài", "di nuovo"), w("见", "jiàn", "vedere")] },
  { id: "g12", cat: "social", it: "Siamo un gruppo", zh: "我们是一个团队", py: "wǒmen shì yí ge tuánduì",
    words: [w("我们", "wǒmen", "noi"), w("是", "shì", "essere"), w("一", "yí", "un"), w("个", "ge", "classificatore"), w("团队", "tuánduì", "gruppo / team")] },
];

window.CAT_LABELS = {
  all: "Tutte",
  sopravvivenza: "Sopravvivenza",
  numeri: "Numeri e soldi",
  cibo: "Cibo",
  trasporti: "Trasporti",
  hotel: "Hotel e shopping",
  social: "Social / gruppo",
};
